### ISSUE TITLE
Add support for `mindreader-node-oneblock-suffix`

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/firehose-arweave#1]
`mindreader-node-oneblock-suffix` is not a supported configuration option. It should be added to be in line with ethereum firehose

**Comment by matthewdarwin** [comment]
Also `mindreader-node-merge-and-store-directly` and `mindreader-node-enforce-peers`

**Comment by maoueh** [comment]
> mindreader-node-merge-and-store-directly

We are removing that setting, now `mindreader-node-merge-threshold-block-age` can take the values: `'never'`, `'always'` and a `<duration>`.

Behavior was not clear with the other flag. Those changes will make it through on `sf-ethereum` and other chains, `firehose-arweave` will act as a testbed.

**Comment by matthewdarwin** [comment]
+1 This is more clear.

**Comment by maoueh** [comment]
> mindreader-node-enforce-peers

This was heavily Ethereum centric and the implementation relied on internal `Geth` RPC calls which would need to be ported  with some investigation. Moreover, it would involve for now dealing with `thegarii` which is not something I want.

If we go with a native node instrumentation, we could check it at that time if it's possible to dynamically add peers.

**Comment by sduchesneau** [comment]
mindreader-node-one-block-suffix has been added by @maoueh on 2022-04-07, can we close this issue ?

**Comment by maoueh** [comment]
Indeed, I did not realize, was simply rename to `mindreader-node-one-block-suffix`.
