### ISSUE TITLE
Allow merger to skip over missing blocks.

### ISSUE THREAD

**Issue by matthewdarwin** [streamingfast/firehose-arweave#3]
How do you make the merger skip over missing blocks?  Since thegarii cannot download all the block files, we have holes.  But the one blocks are all piling up from live, so I'd like to start merging those.  I see no option related to first-streamable-block

```
2022-05-21T03:45:03.527Z (derr) arweave-blockchain {"error": "unable to launch: processing object list: merged blocks skip from 644900 to 648000, you have a hole in your merged block files and need to reprocess or set firstStreamableBlock above this hole"}
```

**Comment by sduchesneau** [comment]
Use this flag: `--common-first-streamable-block=123400` 
^^  this will cause merger to do the following:
* ignore any one-blocks prior to 123400
* accept the first block with number 123400 as the canonical (irreversible) block
* start producing bundle 123400 as soon as it sees a complete chain up to 123500 and continue
* upon restart, it looks at 123400 and then goes through all the other merged blocks until it sees where it ended: then it starts at the next bundle.

In the scenario where you have a (temporary) hole in your one-block-files, simply set the common-first-streamable-block to the first boundary above this hole and it will continue from there.

Let me know if you have any issue while trying this solution.

**Comment by matthewdarwin** [comment]
Ah thanks. I was looking for a "--merger-*" flag.  This is fine.
